// Generated by CoffeeScript 1.6.2
(function() {
  var Scriptures;

  Scriptures = (function() {
    function Scriptures() {
      this.bar = $('.filed-under');
      chrome.runtime.sendMessage({
        file: "stylesheets/scriptures.css"
      }, function(response) {
        return console.log(response);
      });
      this.bind();
    }

    Scriptures.prototype.bind = function() {
      return this.bind_shortcuts();
    };

    Scriptures.prototype.bind_shortcuts = function() {
      var _this = this;

      $('body').on("keypress", "input, textarea", function(e) {
        return e.stopPropagation();
      });
      return $(document).keypress(function(e) {
        e.preventDefault();
        switch (e.keyCode) {
          case 47:
            return console.log("/");
          case 58:
            return _this.seek_verse();
        }
      });
    };

    Scriptures.prototype.seek_verse = function() {
      var li, verse;

      li = $('<li>').addClass('ldsp').addClass('verse');
      verse = $('<input>');
      return this.bar.append(li.append(verse.focus()));
    };

    return Scriptures;

  })();

  $(function() {
    if ($('.filed-under').length > 0) {
      console.log("loaded");
      return new Scriptures;
    }
  });

}).call(this);
