// Generated by CoffeeScript 1.6.2
(function() {
  var Scriptures;

  Scriptures = (function() {
    function Scriptures() {
      this.bars = $('.filed-under');
      this.static_bar = $(this.bars[1]);
      this.dynamic_bar = $(this.bars[0]);
      this.bind();
    }

    Scriptures.prototype.bind = function() {
      this.bind_shortcuts();
      return this.bind_updates();
    };

    Scriptures.prototype.bind_shortcuts = function() {
      var _this = this;

      $('body').on("keypress", "input, textarea, [contenteditable]", function(e) {
        return e.stopPropagation();
      });
      return $(document).keypress(function(e) {
        e.preventDefault();
        switch (e.keyCode) {
          case 47:
            return console.log("/");
          case 58:
            return _this.seek_verse();
        }
      });
    };

    Scriptures.prototype.bind_updates = function() {
      var _this = this;

      this.static_bar.on("keyup", function(e) {
        return _this.dynamic_bar.html(_this.static_bar.children().clone());
      });
      return this.dynamic_bar.on("keyup", function(e) {
        return _this.static_bar.html(_this.dynamic_bar.children().clone());
      });
    };

    Scriptures.prototype.seek_verse = function() {
      var li, verse;

      li = $('<li>').addClass('ldsp').addClass('verse');
      verse = $('<div>');
      verse.attr("contenteditable", "true");
      verse.addClass("bar_input");
      this.bars.append(li.append(verse));
      return verse.focus();
    };

    Scriptures.prototype.auto_size = function(target) {
      console.log("changed");
      return target.css('width', target.val().length * 7 + 20);
    };

    return Scriptures;

  })();

  $(function() {
    if ($('.filed-under').length > 0) {
      console.log("loaded");
      return new Scriptures;
    }
  });

}).call(this);
